### ISSUE TITLE
Python 3.7 Compatibility

### ISSUE THREAD

**Issue by orenbenkiki** [cmcqueen/simplerandom#4]
It seems Python 3.7 broke compatibility in the internals of `PyThreadState`, so building `simplerandom` in 3.7 fails with the error:

```
cython/_iterators_cython.c:29454:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
```

See for example https://github.com/mcfletch/pyopengl/issues/11 which encountered the same problem.

**Comment by cmcqueen** [comment]
Please try release 0.13.1. I have created it using Cython 0.28.5. Hopefully this is compatible with Python 3.7, however I haven't tried it myself since I don't currently have Python 3.7 on a Linux system.

**Comment by cmcqueen** [comment]
Have you had a chance to try 0.13.1?

**Comment by orenbenkiki** [comment]
Sorry for the late response - was on vacation.

Yes, I just tried it w/ 0.13.1 and it works on both 3.6 and 3.7.

Thanks!

Oren.

**Comment by cmcqueen** [comment]
I've now updated this for Python 3.8 too.
